// بعد التعديلات على pricingTiers array فقط

const pricingTiers: PricingTier[] = [
  {
    name: "Free",
    description: "Try El 3atawla free for 1 month",
    price: "$0",
    billingPeriod: "for 1 month",
    features: [
      { text: "CAD to Revit conversion (basic)", included: true },
      { text: "Single user access", included: true },
      { text: "Auto-updates for 1 month", included: true },
      { text: "Community support", included: true },
      { text: "Social sharing renewal required", included: true, tooltip: "After 1 month, renew by sharing posts on LinkedIn and Facebook" },
      { text: "Basic mapping features", included: true },
      { text: "No customizations", included: false },
      { text: "No batch processing", included: false },
    ],
    buttonText: "Start Free Trial",
  },
  {
    name: "Pro",
    description: "Free for 3 months with social support",
    price: "$0",
    billingPeriod: "for 3 months",
    features: [
      { text: "Full CAD to Revit conversion", included: true },
      { text: "3-month auto-updates", included: true },
      { text: "Access to support group", included: true },
      { text: "1 free plugin customization / 3 months", included: true },
      { text: "Social interaction required", included: true, tooltip: "Like & comment on YouTube, share the plugin on LinkedIn & Facebook, and write 2 nice posts" },
      { text: "Advanced mapping rules", included: true },
      { text: "Unlimited batch processing", included: true },
    ],
    highlighted: true,
    badge: "Content Creator Plan",
    buttonText: "Join Pro Plan",
  },
  {
    name: "VIP 🔥",
    description: "Exclusive annual plan with special benefits",
    price: "$50",
    billingPeriod: "per year",
    features: [
      { text: "Everything in Pro plan", included: true },
      { text: "VIP-only support group", included: true },
      { text: "24/7 priority support", included: true },
      { text: "Lifetime auto-updates", included: true },
      { text: "Suggest features or plugins", included: true, tooltip: "We build your idea and release it as a plugin update" },
      { text: "Early access to beta features", included: true },
      { text: "Recognition as VIP supporter", included: true },
    ],
    buttonText: "Upgrade to VIP",
  },
];
